from .KNNClassifier import KNNClassifier
from .KMCClassifier import KMCClassifier
from .MultimodalNaiveBayesianClassification import MultimodalNaiveBayesianClassification
from .OvALogisticClassification import OvALogisticClassification
from .Conf import LogisticClfConfig
